# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
use_frameworks!
target 'ColourMemory' do
    pod 'Cartography'
    pod 'FMDB/standalone'
    pod 'AFNetworking'
    pod 'MBProgressHUD'
    pod 'SnapKit'      		 , '~> 3.2.0'
end

